"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Scene = exports.Plugin = exports.Manager = exports.globalJSONClassRegistry = exports.JSONClassRegistry = exports.requirementToString = exports.filterRequirements = exports.Entity = exports.DefaultManager = exports.DefaultDescriptorManager = exports.Component = exports.Loop = exports.EventLoop = exports.TouchInputHandler = exports.TouchInputEvent = exports.ResizeInputHandler = exports.ResizeInputEvent = exports.MouseInputHandler = exports.MouseWheelInputEvent = exports.MouseInputEvent = exports.KeyboardInputHandler = exports.KeyboardInputEvent = exports.InputHandler = exports.InputEvent = exports.InputButton = exports.InputAxis = exports.Input = exports.RunOnUpdatePlugin = exports.EventListener = exports.FullScreenCanvas = exports.RendererHandler = exports.Renderer = exports.Time = exports.ImageAsset = exports.RawJSONAsset = exports.JSONAsset = exports.Assets = exports.Asset = exports.TransformComponent = exports.TransformComponentManager = exports.RenderableComponent = exports.RunOnUpdateComponent = exports.Transform3D = exports.Transform2D = exports.Camera3DManager = exports.Camera3D = exports.Camera2DControlManager = exports.Camera2DControl = exports.Camera2DManager = exports.Camera2D = void 0;
exports.equals = exports.projectPointOnAxis = exports.sign = exports.getTangentAngle = exports.getPointFromAngle = exports.getAngleFromPoint = exports.getAngleBetweenPoints = exports.getRotationFromMat2d = exports.vec2FromAngle = exports.angleVec2 = exports.clamp = exports.toRgba = exports.toRgb = exports.toHex = exports.HALF_PI = exports.TAU = exports.EPSILON = exports.RAD_TO_DEG = exports.DEG_TO_RAD = exports.radToDeg = exports.degToRad = exports.decomposeMat2d = exports.composeMat2d = exports.Canvas = exports.ToFromJSONEventEmitter = void 0;
var components_1 = require("./components");
Object.defineProperty(exports, "Camera2D", { enumerable: true, get: function () { return components_1.Camera2D; } });
Object.defineProperty(exports, "Camera2DManager", { enumerable: true, get: function () { return components_1.Camera2DManager; } });
Object.defineProperty(exports, "Camera2DControl", { enumerable: true, get: function () { return components_1.Camera2DControl; } });
Object.defineProperty(exports, "Camera2DControlManager", { enumerable: true, get: function () { return components_1.Camera2DControlManager; } });
Object.defineProperty(exports, "Camera3D", { enumerable: true, get: function () { return components_1.Camera3D; } });
Object.defineProperty(exports, "Camera3DManager", { enumerable: true, get: function () { return components_1.Camera3DManager; } });
Object.defineProperty(exports, "Transform2D", { enumerable: true, get: function () { return components_1.Transform2D; } });
Object.defineProperty(exports, "Transform3D", { enumerable: true, get: function () { return components_1.Transform3D; } });
Object.defineProperty(exports, "RunOnUpdateComponent", { enumerable: true, get: function () { return components_1.RunOnUpdateComponent; } });
Object.defineProperty(exports, "RenderableComponent", { enumerable: true, get: function () { return components_1.RenderableComponent; } });
Object.defineProperty(exports, "TransformComponentManager", { enumerable: true, get: function () { return components_1.TransformComponentManager; } });
Object.defineProperty(exports, "TransformComponent", { enumerable: true, get: function () { return components_1.TransformComponent; } });
var plugins_1 = require("./plugins");
Object.defineProperty(exports, "Asset", { enumerable: true, get: function () { return plugins_1.Asset; } });
Object.defineProperty(exports, "Assets", { enumerable: true, get: function () { return plugins_1.Assets; } });
Object.defineProperty(exports, "JSONAsset", { enumerable: true, get: function () { return plugins_1.JSONAsset; } });
Object.defineProperty(exports, "RawJSONAsset", { enumerable: true, get: function () { return plugins_1.RawJSONAsset; } });
Object.defineProperty(exports, "ImageAsset", { enumerable: true, get: function () { return plugins_1.ImageAsset; } });
Object.defineProperty(exports, "Time", { enumerable: true, get: function () { return plugins_1.Time; } });
Object.defineProperty(exports, "Renderer", { enumerable: true, get: function () { return plugins_1.Renderer; } });
Object.defineProperty(exports, "RendererHandler", { enumerable: true, get: function () { return plugins_1.RendererHandler; } });
Object.defineProperty(exports, "FullScreenCanvas", { enumerable: true, get: function () { return plugins_1.FullScreenCanvas; } });
Object.defineProperty(exports, "EventListener", { enumerable: true, get: function () { return plugins_1.EventListener; } });
Object.defineProperty(exports, "RunOnUpdatePlugin", { enumerable: true, get: function () { return plugins_1.RunOnUpdatePlugin; } });
Object.defineProperty(exports, "Input", { enumerable: true, get: function () { return plugins_1.Input; } });
Object.defineProperty(exports, "InputAxis", { enumerable: true, get: function () { return plugins_1.InputAxis; } });
Object.defineProperty(exports, "InputButton", { enumerable: true, get: function () { return plugins_1.InputButton; } });
Object.defineProperty(exports, "InputEvent", { enumerable: true, get: function () { return plugins_1.InputEvent; } });
Object.defineProperty(exports, "InputHandler", { enumerable: true, get: function () { return plugins_1.InputHandler; } });
Object.defineProperty(exports, "KeyboardInputEvent", { enumerable: true, get: function () { return plugins_1.KeyboardInputEvent; } });
Object.defineProperty(exports, "KeyboardInputHandler", { enumerable: true, get: function () { return plugins_1.KeyboardInputHandler; } });
Object.defineProperty(exports, "MouseInputEvent", { enumerable: true, get: function () { return plugins_1.MouseInputEvent; } });
Object.defineProperty(exports, "MouseWheelInputEvent", { enumerable: true, get: function () { return plugins_1.MouseWheelInputEvent; } });
Object.defineProperty(exports, "MouseInputHandler", { enumerable: true, get: function () { return plugins_1.MouseInputHandler; } });
Object.defineProperty(exports, "ResizeInputEvent", { enumerable: true, get: function () { return plugins_1.ResizeInputEvent; } });
Object.defineProperty(exports, "ResizeInputHandler", { enumerable: true, get: function () { return plugins_1.ResizeInputHandler; } });
Object.defineProperty(exports, "TouchInputEvent", { enumerable: true, get: function () { return plugins_1.TouchInputEvent; } });
Object.defineProperty(exports, "TouchInputHandler", { enumerable: true, get: function () { return plugins_1.TouchInputHandler; } });
Object.defineProperty(exports, "EventLoop", { enumerable: true, get: function () { return plugins_1.EventLoop; } });
Object.defineProperty(exports, "Loop", { enumerable: true, get: function () { return plugins_1.Loop; } });
var Component_1 = require("./Component");
Object.defineProperty(exports, "Component", { enumerable: true, get: function () { return Component_1.Component; } });
var DefaultDescriptorManager_1 = require("./DefaultDescriptorManager");
Object.defineProperty(exports, "DefaultDescriptorManager", { enumerable: true, get: function () { return DefaultDescriptorManager_1.DefaultDescriptorManager; } });
var DefaultManager_1 = require("./DefaultManager");
Object.defineProperty(exports, "DefaultManager", { enumerable: true, get: function () { return DefaultManager_1.DefaultManager; } });
var Entity_1 = require("./Entity");
Object.defineProperty(exports, "Entity", { enumerable: true, get: function () { return Entity_1.Entity; } });
var IRequirement_1 = require("./IRequirement");
Object.defineProperty(exports, "filterRequirements", { enumerable: true, get: function () { return IRequirement_1.filterRequirements; } });
Object.defineProperty(exports, "requirementToString", { enumerable: true, get: function () { return IRequirement_1.requirementToString; } });
var JSONClassRegistry_1 = require("./JSONClassRegistry");
Object.defineProperty(exports, "JSONClassRegistry", { enumerable: true, get: function () { return JSONClassRegistry_1.JSONClassRegistry; } });
Object.defineProperty(exports, "globalJSONClassRegistry", { enumerable: true, get: function () { return JSONClassRegistry_1.globalJSONClassRegistry; } });
var Manager_1 = require("./Manager");
Object.defineProperty(exports, "Manager", { enumerable: true, get: function () { return Manager_1.Manager; } });
var Plugin_1 = require("./Plugin");
Object.defineProperty(exports, "Plugin", { enumerable: true, get: function () { return Plugin_1.Plugin; } });
var Scene_1 = require("./Scene");
Object.defineProperty(exports, "Scene", { enumerable: true, get: function () { return Scene_1.Scene; } });
var ToFromJSONEventEmitter_1 = require("./ToFromJSONEventEmitter");
Object.defineProperty(exports, "ToFromJSONEventEmitter", { enumerable: true, get: function () { return ToFromJSONEventEmitter_1.ToFromJSONEventEmitter; } });
var Canvas_1 = require("./Canvas");
Object.defineProperty(exports, "Canvas", { enumerable: true, get: function () { return Canvas_1.Canvas; } });
var math_1 = require("./math");
Object.defineProperty(exports, "composeMat2d", { enumerable: true, get: function () { return math_1.composeMat2d; } });
Object.defineProperty(exports, "decomposeMat2d", { enumerable: true, get: function () { return math_1.decomposeMat2d; } });
Object.defineProperty(exports, "degToRad", { enumerable: true, get: function () { return math_1.degToRad; } });
Object.defineProperty(exports, "radToDeg", { enumerable: true, get: function () { return math_1.radToDeg; } });
Object.defineProperty(exports, "DEG_TO_RAD", { enumerable: true, get: function () { return math_1.DEG_TO_RAD; } });
Object.defineProperty(exports, "RAD_TO_DEG", { enumerable: true, get: function () { return math_1.RAD_TO_DEG; } });
Object.defineProperty(exports, "EPSILON", { enumerable: true, get: function () { return math_1.EPSILON; } });
Object.defineProperty(exports, "TAU", { enumerable: true, get: function () { return math_1.TAU; } });
Object.defineProperty(exports, "HALF_PI", { enumerable: true, get: function () { return math_1.HALF_PI; } });
Object.defineProperty(exports, "toHex", { enumerable: true, get: function () { return math_1.toHex; } });
Object.defineProperty(exports, "toRgb", { enumerable: true, get: function () { return math_1.toRgb; } });
Object.defineProperty(exports, "toRgba", { enumerable: true, get: function () { return math_1.toRgba; } });
Object.defineProperty(exports, "clamp", { enumerable: true, get: function () { return math_1.clamp; } });
Object.defineProperty(exports, "angleVec2", { enumerable: true, get: function () { return math_1.angleVec2; } });
Object.defineProperty(exports, "vec2FromAngle", { enumerable: true, get: function () { return math_1.vec2FromAngle; } });
Object.defineProperty(exports, "getRotationFromMat2d", { enumerable: true, get: function () { return math_1.getRotationFromMat2d; } });
Object.defineProperty(exports, "getAngleBetweenPoints", { enumerable: true, get: function () { return math_1.getAngleBetweenPoints; } });
Object.defineProperty(exports, "getAngleFromPoint", { enumerable: true, get: function () { return math_1.getAngleFromPoint; } });
Object.defineProperty(exports, "getPointFromAngle", { enumerable: true, get: function () { return math_1.getPointFromAngle; } });
Object.defineProperty(exports, "getTangentAngle", { enumerable: true, get: function () { return math_1.getTangentAngle; } });
Object.defineProperty(exports, "sign", { enumerable: true, get: function () { return math_1.sign; } });
Object.defineProperty(exports, "projectPointOnAxis", { enumerable: true, get: function () { return math_1.projectPointOnAxis; } });
Object.defineProperty(exports, "equals", { enumerable: true, get: function () { return math_1.equals; } });
