"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Canvas = exports.ToFromJSONEventEmitter = exports.Scene = exports.Plugin = exports.Manager = exports.globalJSONClassRegistry = exports.JSONClassRegistry = exports.requirementToString = exports.filterRequirements = exports.Entity = exports.DefaultManager = exports.DefaultDescriptorManager = exports.Component = exports.Loop = exports.EventLoop = exports.TouchInputHandler = exports.TouchInputEvent = exports.ResizeInputHandler = exports.ResizeInputEvent = exports.MouseInputHandler = exports.MouseWheelInputEvent = exports.MouseInputEvent = exports.KeyboardInputHandler = exports.KeyboardInputEvent = exports.InputHandler = exports.InputEvent = exports.InputButton = exports.InputAxis = exports.Input = exports.RunOnUpdatePlugin = exports.EventListener = exports.FullScreenCanvas = exports.RendererHandler = exports.Renderer = exports.Time = exports.ImageAsset = exports.RawJSONAsset = exports.JSONAsset = exports.Assets = exports.Asset = exports.RenderableComponent = exports.RunOnUpdateComponent = void 0;
var components_1 = require("./components");
Object.defineProperty(exports, "RunOnUpdateComponent", { enumerable: true, get: function () { return components_1.RunOnUpdateComponent; } });
Object.defineProperty(exports, "RenderableComponent", { enumerable: true, get: function () { return components_1.RenderableComponent; } });
var plugins_1 = require("./plugins");
Object.defineProperty(exports, "Asset", { enumerable: true, get: function () { return plugins_1.Asset; } });
Object.defineProperty(exports, "Assets", { enumerable: true, get: function () { return plugins_1.Assets; } });
Object.defineProperty(exports, "JSONAsset", { enumerable: true, get: function () { return plugins_1.JSONAsset; } });
Object.defineProperty(exports, "RawJSONAsset", { enumerable: true, get: function () { return plugins_1.RawJSONAsset; } });
Object.defineProperty(exports, "ImageAsset", { enumerable: true, get: function () { return plugins_1.ImageAsset; } });
Object.defineProperty(exports, "Time", { enumerable: true, get: function () { return plugins_1.Time; } });
Object.defineProperty(exports, "Renderer", { enumerable: true, get: function () { return plugins_1.Renderer; } });
Object.defineProperty(exports, "RendererHandler", { enumerable: true, get: function () { return plugins_1.RendererHandler; } });
Object.defineProperty(exports, "FullScreenCanvas", { enumerable: true, get: function () { return plugins_1.FullScreenCanvas; } });
Object.defineProperty(exports, "EventListener", { enumerable: true, get: function () { return plugins_1.EventListener; } });
Object.defineProperty(exports, "RunOnUpdatePlugin", { enumerable: true, get: function () { return plugins_1.RunOnUpdatePlugin; } });
Object.defineProperty(exports, "Input", { enumerable: true, get: function () { return plugins_1.Input; } });
Object.defineProperty(exports, "InputAxis", { enumerable: true, get: function () { return plugins_1.InputAxis; } });
Object.defineProperty(exports, "InputButton", { enumerable: true, get: function () { return plugins_1.InputButton; } });
Object.defineProperty(exports, "InputEvent", { enumerable: true, get: function () { return plugins_1.InputEvent; } });
Object.defineProperty(exports, "InputHandler", { enumerable: true, get: function () { return plugins_1.InputHandler; } });
Object.defineProperty(exports, "KeyboardInputEvent", { enumerable: true, get: function () { return plugins_1.KeyboardInputEvent; } });
Object.defineProperty(exports, "KeyboardInputHandler", { enumerable: true, get: function () { return plugins_1.KeyboardInputHandler; } });
Object.defineProperty(exports, "MouseInputEvent", { enumerable: true, get: function () { return plugins_1.MouseInputEvent; } });
Object.defineProperty(exports, "MouseWheelInputEvent", { enumerable: true, get: function () { return plugins_1.MouseWheelInputEvent; } });
Object.defineProperty(exports, "MouseInputHandler", { enumerable: true, get: function () { return plugins_1.MouseInputHandler; } });
Object.defineProperty(exports, "ResizeInputEvent", { enumerable: true, get: function () { return plugins_1.ResizeInputEvent; } });
Object.defineProperty(exports, "ResizeInputHandler", { enumerable: true, get: function () { return plugins_1.ResizeInputHandler; } });
Object.defineProperty(exports, "TouchInputEvent", { enumerable: true, get: function () { return plugins_1.TouchInputEvent; } });
Object.defineProperty(exports, "TouchInputHandler", { enumerable: true, get: function () { return plugins_1.TouchInputHandler; } });
Object.defineProperty(exports, "EventLoop", { enumerable: true, get: function () { return plugins_1.EventLoop; } });
Object.defineProperty(exports, "Loop", { enumerable: true, get: function () { return plugins_1.Loop; } });
var Component_1 = require("./Component");
Object.defineProperty(exports, "Component", { enumerable: true, get: function () { return Component_1.Component; } });
var DefaultDescriptorManager_1 = require("./DefaultDescriptorManager");
Object.defineProperty(exports, "DefaultDescriptorManager", { enumerable: true, get: function () { return DefaultDescriptorManager_1.DefaultDescriptorManager; } });
var DefaultManager_1 = require("./DefaultManager");
Object.defineProperty(exports, "DefaultManager", { enumerable: true, get: function () { return DefaultManager_1.DefaultManager; } });
var Entity_1 = require("./Entity");
Object.defineProperty(exports, "Entity", { enumerable: true, get: function () { return Entity_1.Entity; } });
var IRequirement_1 = require("./IRequirement");
Object.defineProperty(exports, "filterRequirements", { enumerable: true, get: function () { return IRequirement_1.filterRequirements; } });
Object.defineProperty(exports, "requirementToString", { enumerable: true, get: function () { return IRequirement_1.requirementToString; } });
var JSONClassRegistry_1 = require("./JSONClassRegistry");
Object.defineProperty(exports, "JSONClassRegistry", { enumerable: true, get: function () { return JSONClassRegistry_1.JSONClassRegistry; } });
Object.defineProperty(exports, "globalJSONClassRegistry", { enumerable: true, get: function () { return JSONClassRegistry_1.globalJSONClassRegistry; } });
var Manager_1 = require("./Manager");
Object.defineProperty(exports, "Manager", { enumerable: true, get: function () { return Manager_1.Manager; } });
var Plugin_1 = require("./Plugin");
Object.defineProperty(exports, "Plugin", { enumerable: true, get: function () { return Plugin_1.Plugin; } });
var Scene_1 = require("./Scene");
Object.defineProperty(exports, "Scene", { enumerable: true, get: function () { return Scene_1.Scene; } });
var ToFromJSONEventEmitter_1 = require("./ToFromJSONEventEmitter");
Object.defineProperty(exports, "ToFromJSONEventEmitter", { enumerable: true, get: function () { return ToFromJSONEventEmitter_1.ToFromJSONEventEmitter; } });
var Canvas_1 = require("./Canvas");
Object.defineProperty(exports, "Canvas", { enumerable: true, get: function () { return Canvas_1.Canvas; } });
