"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SpriteSheet = exports.SpriteManager = exports.SpriteClip = exports.Sprite = void 0;
var Sprite_1 = require("./Sprite");
Object.defineProperty(exports, "Sprite", { enumerable: true, get: function () { return Sprite_1.Sprite; } });
var SpriteClip_1 = require("./SpriteClip");
Object.defineProperty(exports, "SpriteClip", { enumerable: true, get: function () { return SpriteClip_1.SpriteClip; } });
var SpriteManager_1 = require("./SpriteManager");
Object.defineProperty(exports, "SpriteManager", { enumerable: true, get: function () { return SpriteManager_1.SpriteManager; } });
var SpriteSheet_1 = require("./SpriteSheet");
Object.defineProperty(exports, "SpriteSheet", { enumerable: true, get: function () { return SpriteSheet_1.SpriteSheet; } });
