"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CtxRendererHandler = exports.CtxRenderer = exports.TransformCtxRendererHandler = exports.SpriteCtxRendererHandler = void 0;
var _2d_1 = require("./2d");
Object.defineProperty(exports, "SpriteCtxRendererHandler", { enumerable: true, get: function () { return _2d_1.SpriteCtxRendererHandler; } });
Object.defineProperty(exports, "TransformCtxRendererHandler", { enumerable: true, get: function () { return _2d_1.TransformCtxRendererHandler; } });
var CtxRenderer_1 = require("./CtxRenderer");
Object.defineProperty(exports, "CtxRenderer", { enumerable: true, get: function () { return CtxRenderer_1.CtxRenderer; } });
var CtxRendererHandler_1 = require("./CtxRendererHandler");
Object.defineProperty(exports, "CtxRendererHandler", { enumerable: true, get: function () { return CtxRendererHandler_1.CtxRendererHandler; } });
